# Generated by Django 2.2.13 on 2020-09-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20200908_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], default='Female', max_length=120),
        ),
    ]
